#ifndef __MESHGEMS_CVM_SHORT_NAMES__
#define __MESHGEMS_CVM_SHORT_NAMES__

/**
 * Short names. Allow the caller to omit the meshgems_ prefix.
 */

#ifndef MESHGEMS_NO_SHORT_NAMES
#define cvm_get_version_ident_string meshgems_cvm_get_version_ident_string
#define cvm_get_version_major meshgems_cvm_get_version_major
#define cvm_get_version_minor meshgems_cvm_get_version_minor
#define cvm_get_version_patch meshgems_cvm_get_version_patch
#define cvm_get_version_string meshgems_cvm_get_version_string
#define cvm_session_compute_mesh meshgems_cvm_session_compute_mesh
#define cvm_session_delete meshgems_cvm_session_delete
#define cvm_session_get_distance_to_original_surface_sizemap meshgems_cvm_session_get_distance_to_original_surface_sizemap
#define cvm_session_get_distance_to_original_surface_sizemap_abs meshgems_cvm_session_get_distance_to_original_surface_sizemap_abs
#define cvm_session_get_edge_global_count meshgems_cvm_session_get_edge_global_count
#define cvm_session_get_mesh meshgems_cvm_session_get_mesh
#define cvm_session_get_sizemap meshgems_cvm_session_get_sizemap
#define cvm_session_get_subdomain_count meshgems_cvm_session_get_subdomain_count
#define cvm_session_get_subdomain_edges_global_index meshgems_cvm_session_get_subdomain_edges_global_index
#define cvm_session_get_subdomain_edges_global_index_count meshgems_cvm_session_get_subdomain_edges_global_index_count
#define cvm_session_get_subdomain_index meshgems_cvm_session_get_subdomain_index
#define cvm_session_get_subdomain_mesh meshgems_cvm_session_get_subdomain_mesh
#define cvm_session_get_subdomain_sizemap meshgems_cvm_session_get_subdomain_sizemap
#define cvm_session_get_subdomain_tetrahedra_global_index meshgems_cvm_session_get_subdomain_tetrahedra_global_index
#define cvm_session_get_subdomain_tetrahedra_global_index_count meshgems_cvm_session_get_subdomain_tetrahedra_global_index_count
#define cvm_session_get_subdomain_triangles_global_index meshgems_cvm_session_get_subdomain_triangles_global_index
#define cvm_session_get_subdomain_triangles_global_index_count meshgems_cvm_session_get_subdomain_triangles_global_index_count
#define cvm_session_get_subdomain_vertices_global_index meshgems_cvm_session_get_subdomain_vertices_global_index
#define cvm_session_get_subdomain_vertices_global_index_count meshgems_cvm_session_get_subdomain_vertices_global_index_count
#define cvm_session_get_surface_mesh meshgems_cvm_session_get_surface_mesh
#define cvm_session_get_tetrahedron_global_count meshgems_cvm_session_get_tetrahedron_global_count
#define cvm_session_get_triangle_global_count meshgems_cvm_session_get_triangle_global_count
#define cvm_session_get_vertex_global_count meshgems_cvm_session_get_vertex_global_count
#define cvm_session_new meshgems_cvm_session_new
#define cvm_session_regain_mesh meshgems_cvm_session_regain_mesh
#define cvm_session_regain_sizemap meshgems_cvm_session_regain_sizemap
#define cvm_session_regain_subdomain_mesh meshgems_cvm_session_regain_subdomain_mesh
#define cvm_session_regain_subdomain_sizemap meshgems_cvm_session_regain_subdomain_sizemap
#define cvm_session_regain_surface_mesh meshgems_cvm_session_regain_surface_mesh
#define cvm_session_set_input_mesh meshgems_cvm_session_set_input_mesh
#define cvm_session_set_input_wrapped_surface_mesh meshgems_cvm_session_set_input_wrapped_surface_mesh
#define cvm_session_set_interrupt_callback meshgems_cvm_session_set_interrupt_callback
#define cvm_session_set_message_callback meshgems_cvm_session_set_message_callback
#define cvm_session_set_param meshgems_cvm_session_set_param
#define cvm_session_set_size_specification meshgems_cvm_session_set_size_specification
#define cvm_session_set_sizemap meshgems_cvm_session_set_sizemap
#define cvm_session_set_tetrahedron_quality_callback meshgems_cvm_session_set_tetrahedron_quality_callback
#define cvm_size_specification_add_boundary_layer_arithmetic_constraint_on_face meshgems_cvm_size_specification_add_boundary_layer_arithmetic_constraint_on_face
#define cvm_size_specification_add_boundary_layer_arithmetic_constraint_on_face_tag meshgems_cvm_size_specification_add_boundary_layer_arithmetic_constraint_on_face_tag
#define cvm_size_specification_add_boundary_layer_arithmetic_constraint_on_face_tag_in_subdomain meshgems_cvm_size_specification_add_boundary_layer_arithmetic_constraint_on_face_tag_in_subdomain
#define cvm_size_specification_add_boundary_layer_arithmetic_constraint_on_subdomain meshgems_cvm_size_specification_add_boundary_layer_arithmetic_constraint_on_subdomain
#define cvm_size_specification_add_boundary_layer_distribution_constraint_on_face meshgems_cvm_size_specification_add_boundary_layer_distribution_constraint_on_face
#define cvm_size_specification_add_boundary_layer_distribution_constraint_on_face_tag meshgems_cvm_size_specification_add_boundary_layer_distribution_constraint_on_face_tag
#define cvm_size_specification_add_boundary_layer_distribution_constraint_on_face_tag_in_subdomain meshgems_cvm_size_specification_add_boundary_layer_distribution_constraint_on_face_tag_in_subdomain
#define cvm_size_specification_add_boundary_layer_distribution_constraint_on_subdomain meshgems_cvm_size_specification_add_boundary_layer_distribution_constraint_on_subdomain
#define cvm_size_specification_add_boundary_layer_geometric_constraint_on_face meshgems_cvm_size_specification_add_boundary_layer_geometric_constraint_on_face
#define cvm_size_specification_add_boundary_layer_geometric_constraint_on_face_tag meshgems_cvm_size_specification_add_boundary_layer_geometric_constraint_on_face_tag
#define cvm_size_specification_add_boundary_layer_geometric_constraint_on_face_tag_in_subdomain meshgems_cvm_size_specification_add_boundary_layer_geometric_constraint_on_face_tag_in_subdomain
#define cvm_size_specification_add_boundary_layer_geometric_constraint_on_subdomain meshgems_cvm_size_specification_add_boundary_layer_geometric_constraint_on_subdomain
#define cvm_size_specification_add_boundary_layer_null_constraint_on_face meshgems_cvm_size_specification_add_boundary_layer_null_constraint_on_face
#define cvm_size_specification_add_boundary_layer_null_constraint_on_face_tag meshgems_cvm_size_specification_add_boundary_layer_null_constraint_on_face_tag
#define cvm_size_specification_add_boundary_layer_null_constraint_on_face_tag_in_subdomain meshgems_cvm_size_specification_add_boundary_layer_null_constraint_on_face_tag_in_subdomain
#define cvm_size_specification_add_boundary_layer_null_constraint_on_subdomain meshgems_cvm_size_specification_add_boundary_layer_null_constraint_on_subdomain
#define cvm_size_specification_add_boundary_layer_uniform_constraint_on_face meshgems_cvm_size_specification_add_boundary_layer_uniform_constraint_on_face
#define cvm_size_specification_add_boundary_layer_uniform_constraint_on_face_tag meshgems_cvm_size_specification_add_boundary_layer_uniform_constraint_on_face_tag
#define cvm_size_specification_add_boundary_layer_uniform_constraint_on_face_tag_in_subdomain meshgems_cvm_size_specification_add_boundary_layer_uniform_constraint_on_face_tag_in_subdomain
#define cvm_size_specification_add_boundary_layer_uniform_constraint_on_subdomain meshgems_cvm_size_specification_add_boundary_layer_uniform_constraint_on_subdomain
#define cvm_size_specification_add_growth_constraint_on_subdomain meshgems_cvm_size_specification_add_growth_constraint_on_subdomain
#define cvm_size_specification_delete meshgems_cvm_size_specification_delete
#define cvm_size_specification_new meshgems_cvm_size_specification_new
#define cvm_session_t meshgems_cvm_session_t
#define cvm_size_specification_boundary_layer_distribution_t meshgems_cvm_size_specification_boundary_layer_distribution_t
#define cvm_size_specification_t meshgems_cvm_size_specification_t
#define cvm_tetrahedron_quality_callback_t meshgems_cvm_tetrahedron_quality_callback_t
#define CVM_H MESHGEMS_CVM_H
#endif /* MESHGEMS_NO_SHORT_NAMES */
#endif /* __MESHGEMS_CVM_SHORT_NAMES__ */
